#!/bin/bash

echo "     _.---._    /\\"
echo "  ./'       '--'\//"
echo " ./              o \          .-----."
echo "/./\  )______   \__ \        ( help! )"
echo "./  / /\ \   | \ \  \ \       /'-----'"
echo "   / /  \ \  | |\ \  \7--- ooo ooo ooo ooo ooo ooo"
