#!/bin/bash

npx eslint src/index.html

branch=`git symbolic-ref --short HEAD`
first_line=`head -n1 $1`
user="A corregir por:usuario1"
verify_user="^("+$user+"):"

if [[ $branch == "hotfix" && ! $first_line == $verify_user ]];then

	echo "EL comentario debe incluir:"+$user
	exit 1
fi
exit 0
